Repository poncateam/ponca, pull requests merged in 2025-07, with the labels that each got.

#172 Adding the missing base from the curvature estimator in the Fitting user manual
  CHANGELOG
  doc/src/ponca_module_fitting.mdoc
Labels: bug, doc

#162 Investigation of the random crash in the unit test
  .github/workflows/ContinuousTest.yml
  CHANGELOG
  Ponca/src/Fitting/algebraicSphere.h
  Ponca/src/Fitting/algebraicSphere.hpp
  tests/common/testUtils.h
  tests/src/basket.cpp
  tests/src/fit_line.cpp
  tests/src/gls_paraboloid_der.cpp
  tests/src/projection.cpp
Labels: bug

#167 [WIP] refactor weights
  CHANGELOG
  Ponca/src/Fitting/algebraicSphere.h
  Ponca/src/Fitting/basket.h
  Ponca/src/Fitting/covarianceFit.hpp
  Ponca/src/Fitting/curvature.hpp
  Ponca/src/Fitting/curvatureEstimation.hpp
  Ponca/src/Fitting/defines.h
  Ponca/src/Fitting/linePrimitive.h
  Ponca/src/Fitting/mean.hpp
  Ponca/src/Fitting/mlsSphereFitDer.hpp
  Ponca/src/Fitting/mongePatch.hpp
  Ponca/src/Fitting/orientedSphereFit.hpp
  Ponca/src/Fitting/plane.h
  Ponca/src/Fitting/primitive.h
  Ponca/src/Fitting/sphereFit.hpp
  Ponca/src/Fitting/unorientedSphereFit.hpp
  Ponca/src/Fitting/weightFunc.h
  doc/examples/concepts.hpp
  doc/src/concepts.mdoc
  doc/src/ponca_module_fitting.mdoc
  doc/src/ponca_module_spatialpartitioning.mdoc
  examples/cpp/nanoflann/ponca_nanoflann.cpp
  examples/cpp/pcl/pcl_wrapper.hpp
  examples/cpp/ponca_basic_cpu.cpp
  examples/cpp/ponca_binding.cpp
  examples/cpp/ponca_fit_line.cpp
  examples/cpp/ponca_fit_plane.cpp
  examples/cuda/ponca_ssgls.cu
  tests/src/algebraicsphere_primitive.cpp
  tests/src/basket.cpp
  tests/src/curvature_plane.cpp
  tests/src/curvature_sphere.cpp
  tests/src/dnormal_orthogonal_derivatives.cpp
  tests/src/dnormal_plane.cpp
  tests/src/dnormal_sphere.cpp
  tests/src/dpotential_plane.cpp
  tests/src/dpotential_sphere.cpp
  tests/src/fit_cov.cpp
  tests/src/fit_line.cpp
  tests/src/fit_monge_patch.cpp
  tests/src/fit_plane.cpp
  tests/src/fit_radius_curvature_center.cpp
  tests/src/fit_unoriented.cpp
  tests/src/gls_compare.cpp
  tests/src/gls_paraboloid_der.cpp
  tests/src/gls_sphere_der.cpp
  tests/src/gls_tau.cpp
  tests/src/normal_plane.cpp
  tests/src/normal_sphere.cpp
  tests/src/projection.cpp
  tests/src/scale_space_consistency.cpp
Labels: enhancement
